# Generated by Django 4.1.3 on 2022-11-30 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
import utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='advert.advertcategory')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ends', models.DateTimeField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=utils.utils.advert_picture_directory_path)),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинка',
            },
        ),
        migrations.CreateModel(
            name='AutoBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='advert.autobrand')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(choices=[('b', 'Плохое'), ('m', 'Среднее'), ('g', 'Хорошее')], default='g', max_length=5)),
                ('contact', models.CharField(choices=[('call', 'Позвонить'), ('write', 'Написать'), ('all', 'Любой из указанных')], default='all', max_length=10)),
                ('status', models.CharField(choices=[('published', 'Опубликована'), ('draft', 'В черновике'), ('ban', 'В бане')], default='draft', max_length=20)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('release', models.DateField(blank=True, null=True)),
                ('transmission', models.CharField(choices=[('a', 'Автоматическая'), ('m', 'Механическая'), ('v', 'Вариативная'), ('r', 'Роботизированная')], default='m', max_length=5)),
                ('number_owner', models.IntegerField(blank=True, null=models.CharField(choices=[('a', 'Автоматическая'), ('m', 'Механическая'), ('v', 'Вариативная'), ('r', 'Роботизированная')], default='m', max_length=5))),
                ('color', models.CharField(blank=True, choices=[('white', 'Белый'), ('black', 'Черный'), ('gray', 'Серый'), ('brown', 'Коричневый'), ('red', 'Красный'), ('green', 'Зеленый'), ('blue', 'Синий'), ('pink', 'Розовый')], max_length=15, null=True)),
                ('body_type', models.CharField(choices=[('se', 'Седан'), ('un', 'Универсал'), ('ha', 'Хэтчбек'), ('lb', 'Лифтбек'), ('cp', 'Купе'), ('lm', 'Лимузин'), ('suv', 'Внедорожник'), ('pic', 'Пикап'), ('mn', 'Минивен'), ('fr', 'Фургон'), ('mcra', 'Микроавтобус')], max_length=10)),
                ('engine_volume', models.CharField(blank=True, max_length=10, null=True)),
                ('engine_type', models.CharField(choices=[('p', 'Бензин'), ('g', 'Газ'), ('d', 'Дизель'), ('gb', 'гибридные'), ('e', 'Электро')], default='p', max_length=5)),
                ('drive_unit', models.CharField(blank=True, choices=[('front', 'Передний'), ('real', 'Задний'), ('full', 'Полный'), ('hybrid', 'Гибридный')], max_length=10, null=True)),
                ('mileage', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.autobrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.advertcategory')),
                ('discount', models.ManyToManyField(to='advert.discount')),
                ('pictures', models.ManyToManyField(to='advert.picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advert', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Авто',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
