# Generated by Django 4.1.3 on 2022-12-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_motorbike_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorbike',
            name='color',
            field=models.CharField(choices=[('white', 'Белый'), ('black', 'Черный'), ('gray', 'Серый'), ('brown', 'Коричневый'), ('red', 'Красный'), ('green', 'Зеленый'), ('blue', 'Синий'), ('pink', 'Розовый'), ('violet', 'Фиолетовый')], max_length=10),
        ),
    ]
